[package]
name = "reactor-phys"
version = "0.1.0"
authors = ["Anonymous <_>"]

[dependencies]

[dependencies.int_traits]
git = "https://github.com/tiehuis/int_traits"
rev = "150ff52652cd700ae57e284c547b92673dac91c1"
